name: SDMC Firework Plugin
main: com.silentdarknessmc.firework.Main
description:  >
              SDMC's Firework Plugin
version: 2.2
author: SDMC

commands:
  shoot:
    description: Shoot A Firework From Where You're Standing!